brokerClusterName = livebid-cluster
brokerName = broker-a
brokerId = 0
brokerRole = ASYNC_MASTER
flushDiskType = ASYNC_FLUSH
listenPort = 10911
brokerIP1 = rocketmq-broker
autoCreateTopicEnable = true
autoCreateSubscriptionGroup = true
deleteWhen = 04
fileReservedTime = 48
