env: local

http:
  addr: ":58080"

shopService:
  addr: "127.0.0.1:9001"
  target: "127.0.0.1:9001"

userService:
  addr: "127.0.0.1:9004"
  target: "127.0.0.1:9004"

goodsService:
  addr: "127.0.0.1:9002"
  target: "127.0.0.1:9002"

liveService:
  addr: "127.0.0.1:9007"
  target: "127.0.0.1:9007"

auctionService:
  addr: "127.0.0.1:9003"
  target: "127.0.0.1:9003"

storage:
  endpoint: "http://127.0.0.1:9000"
  publicBaseUrl: "http://127.0.0.1:9000/livebid"
  bucket: "livebid"
  region: "us-east-1"
  accessKeyId: "rustfsadmin"
  secretAccessKey: "rustfsadmin"
  pathStyle: true

jwt:
  secret: "local-dev-jwt-secret-change-me"
  shopIssuer: "livebid-shop"
  userIssuer: "livebid-user"
  accessTokenTTLSeconds: 604800

rpc:
  timeoutSeconds: 3

log:
  level: debug
  encoding: console
  outputs:
    - stdout
  errorOutputs:
    - stderr
  development: true

nacos:
  enabled: true
  servers:
    - host: "127.0.0.1"
      port: 8848
  namespaceId: "livebid-local"

configCenter:
  enabled: false
  dataId: "livebid.local.api-gateway.yaml"
  group: "LIVEBID"
