env: local
grpc:
  addr: ":9003"
mysql:
  dsn: "root:123@tcp(172.31.85.64:3306)/mydb?charset=utf8mb4&parseTime=True&loc=Local"
  autoMigrate: true
  maxOpenConns: 20
  maxIdleConns: 10
  connMaxLifetimeSeconds: 1800
redis:
  addr: "172.31.85.64:6379"
  password: "123456"
  db: 0
rocketmq:
  nameServers:
    - "172.31.85.64:9876"
  producerGroup: "auction-service-producer"
  consumerGroup: "auction-service-consumer"
  topic: "auction_event"
  delayLevel: 4
  maxReconsumeTimes: 5
goods:
  addr: "127.0.0.1:9002"
  target: "127.0.0.1:9002"
live:
  addr: "127.0.0.1:9007"
  target: "127.0.0.1:9007"
workerID: 3
log:
  level: debug
  encoding: console

nacos:
  enabled: true
  servers:
    - host: "127.0.0.1"
      port: 8848
      grpcPort: 9848
  namespaceId: "livebid-local"

configCenter:
  enabled: false
  dataId: "livebid.local.auction-service.yaml"
  group: "LIVEBID"

registry:
  enabled: true
  provider: "nacos"
  serviceName: "auction-service"
  group: "LIVEBID"
  cluster: "default"
  ip: ""
  port: 0
  weight: 1

healthCheck:
  enabled: true
  intervalSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 3
