listen              1935;
max_connections     1000;

http_api {
    enabled         on;
    listen          1985;
}

http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}

rtc_server {
    enabled         on;
    listen          8000;
    candidate       127.0.0.1;
}

vhost __defaultVhost__ {
    min_latency on;
    tcp_nodelay on;

    publish {
        mr off;
    }

    play {
        gop_cache off;
        queue_length 10;
        mw_latency 100;
    }

    rtc {
        enabled     on;
        rtmp_to_rtc on;
    }

    http_hooks {
        enabled      on;
        on_publish   http://api-gateway:58080/api/srs/callbacks/publish;
        on_unpublish http://api-gateway:58080/api/srs/callbacks/unpublish;
    }
}
